import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Mail,
  ClipboardList,
  CalendarClock,
  BookOpen,
  MessageSquare,
  ArrowRight,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

export const Route = createFileRoute("/")({ component: Dashboard });

const tools = [
  { to: "/email", title: "Smart Email Generator", desc: "Draft polished emails in any tone — formal, friendly, or persuasive.", icon: Mail },
  { to: "/summarizer", title: "Meeting Notes Summarizer", desc: "Turn long notes into summaries, decisions, action items & deadlines.", icon: ClipboardList },
  { to: "/planner", title: "AI Task Planner", desc: "Generate prioritized daily or weekly schedules from your task list.", icon: CalendarClock },
  { to: "/research", title: "Research Assistant", desc: "Get structured briefings, insights and recommendations on any topic.", icon: BookOpen },
  { to: "/chat", title: "AI Workplace Chat", desc: "An interactive assistant for any workplace question or quick task.", icon: MessageSquare },
] as const;

function Dashboard() {
  return (
    <div className="mx-auto w-full max-w-6xl space-y-10 p-4 md:p-8">
      <section className="relative overflow-hidden rounded-2xl border bg-card p-8 shadow-soft md:p-12">
        <div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-gradient-brand opacity-20 blur-3xl" />
        <div className="relative max-w-2xl">
          <span className="inline-flex items-center gap-1.5 rounded-full border bg-background/60 px-3 py-1 text-xs font-medium text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5 text-primary" /> AI Workplace Productivity Suite
          </span>
          <h1 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">
            Automate the busywork.{" "}
            <span className="bg-gradient-brand bg-clip-text text-transparent">Focus on the work that matters.</span>
          </h1>
          <p className="mt-4 text-base text-muted-foreground md:text-lg">
            Five AI-powered tools to draft emails, summarize meetings, plan your week, research topics, and answer questions — all in one workspace.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link to="/email" className="inline-flex items-center gap-1.5 rounded-lg bg-gradient-brand px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-glow transition hover:opacity-95">
              Start with Email <ArrowRight className="h-4 w-4" />
            </Link>
            <Link to="/chat" className="inline-flex items-center gap-1.5 rounded-lg border bg-background px-5 py-2.5 text-sm font-medium hover:bg-accent">
              Open AI Chat
            </Link>
          </div>
        </div>
      </section>

      <section>
        <h2 className="mb-4 text-lg font-semibold">Your AI tools</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {tools.map((t) => (
            <Link
              key={t.to}
              to={t.to}
              className="group rounded-xl border bg-card p-5 shadow-soft transition hover:-translate-y-0.5 hover:shadow-glow"
            >
              <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-lg bg-accent text-accent-foreground transition group-hover:bg-gradient-brand group-hover:text-primary-foreground">
                <t.icon className="h-5 w-5" />
              </div>
              <h3 className="font-semibold">{t.title}</h3>
              <p className="mt-1.5 text-sm text-muted-foreground">{t.desc}</p>
              <span className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-primary">
                Open tool <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" />
              </span>
            </Link>
          ))}
        </div>
      </section>

      <section className="rounded-xl border bg-card p-5 shadow-soft">
        <div className="flex gap-3">
          <ShieldCheck className="h-5 w-5 shrink-0 text-primary" />
          <div className="text-sm text-muted-foreground">
            <strong className="text-foreground">Responsible AI notice.</strong>{" "}
            Outputs are generated by AI and may be inaccurate, incomplete, or biased. Always review,
            verify facts, and protect confidential information before sharing AI-generated content.
            Do not paste secrets, personal data, or regulated information into the tools.
          </div>
        </div>
      </section>
    </div>
  );
}
